before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: jRxFUOnzt30jj7H8swYw11JD1ygMEEz3Sg4iyakvkdPPpNLL8wEG0oR8bQhN5c/PkuZXJxSl4bdd8BQS+68rpIRU5qopZbEP0LZay6AVYOWnSZmvmnexxWMyweQ3PS0+6EKTyv+66RxwUirI3/Ds1b2fm+KQfh6fPuAntn8DH9cKmmA7YcUQAorAZmoawcTAa6umKpprlSzT+PHUaz5nII2S5RXews3ZV3RPmqROfBTLir1rKMM5IFdhd+yrFoKNReW/E1PLCYISANbuqArFm7OudIkZZHPOlizX9kzOhl/tQqxWgecJ0nTVtlS5ScT+nFNnzm/smFnkL6Oez/kbOOCP8ze1jR3V9egr7SsDY0pTE6KU0GFCQmQ29NVNUXO1K9H1YrO0PG9lMvkhlaXyCjYZRTfXzb1eSoIYnkgmyqc06Sc7V3/XafSrr6h29sMu1GIEzwZ0V++pnzXgw1o6twD3kMMFtPcL56wPPAG2JCRihNEOyrLEmdOs+E2/cfiR5ZqOYGlwAXZ73Z9K5g20k1y1uvNBGd/fvnZWoDuEMvMX0GfU+szAMywRb1tY6wt5aHXQU4z64yH6DELyrn4TmO5X+1oxt3rDtH8w16BlHWbVJd/y0z3cOvIlupIJHuMcswO3vcEom8mOnXCbjZyZgokujUKrQGQLvw3RixVg8+c= # CRYPTO_AES_KEY
language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
